
export const BUSINESS_TYPE_OPTIONS = [
  { value: "accounting", label: "Accounting" },
  { value: "advertising", label: "Advertising & Marketing" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "animal_care", label: "Animal Care & Veterinary" },
  { value: "architecture", label: "Architecture & Engineering" },
  { value: "automotive", label: "Automotive Services" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "business_services", label: "Business & Professional Services" },
  { value: "catering", label: "Catering & Food Services" },
  { value: "childcare", label: "Childcare & Education" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "computer", label: "Computer & IT Services" },
  { value: "construction", label: "Construction & Contracting" },
  { value: "consulting", label: "Consulting" },
  { value: "dance", label: "Dance & Performing Arts" },
  { value: "dental", label: "Dental Services" },
  { value: "design", label: "Design & Creative Services" },
  { value: "education", label: "Education & Training" },
  { value: "electrical", label: "Electrical Services" },
  { value: "entertainment", label: "Entertainment & Recreation" },
  { value: "event_planning", label: "Event Planning" },
  { value: "financial", label: "Financial Services" },
  { value: "fitness", label: "Fitness & Wellness" },
  { value: "florist", label: "Florist & Garden Services" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "funeral", label: "Funeral Services" },
  { value: "hair_salon", label: "Hair Salon & Barbering" },
  { value: "handyman", label: "Handyman Services" },
  { value: "healthcare", label: "Healthcare Services" },
  { value: "home_improvement", label: "Home Improvement" },
  { value: "insurance", label: "Insurance" },
  { value: "landscaping", label: "Landscaping & Lawn Care" },
  { value: "laundry", label: "Laundry & Dry Cleaning" },
  { value: "legal", label: "Legal Services" },
  { value: "logistics", label: "Logistics & Transportation" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "massage", label: "Massage Therapy" },
  { value: "medical", label: "Medical Services" },
  { value: "music", label: "Music & Audio Services" },
  { value: "nonprofit", label: "Nonprofit Organization" },
  { value: "optometry", label: "Optometry & Vision Care" },
  { value: "painting", label: "Painting Services" },
  { value: "pest_control", label: "Pest Control" },
  { value: "pet_services", label: "Pet Services & Grooming" },
  { value: "photography", label: "Photography & Videography" },
  { value: "plumbing", label: "Plumbing Services" },
  { value: "printing", label: "Printing & Publishing" },
  { value: "real_estate", label: "Real Estate" },
  { value: "restaurant", label: "Restaurant & Food Service" },
  { value: "retail", label: "Retail & Shopping" },
  { value: "roofing", label: "Roofing Services" },
  { value: "security", label: "Security Services" },
  { value: "spa", label: "Spa & Wellness" },
  { value: "storage", label: "Storage & Moving" },
  { value: "taxi", label: "Taxi & Ride Services" },
  { value: "technology", label: "Technology Services" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "travel", label: "Travel & Tourism" },
  { value: "tutoring", label: "Tutoring & Academic Support" },
  { value: "waste_management", label: "Waste Management" },
  { value: "wedding", label: "Wedding Services" },
  { value: "other", label: "Other" }
];

export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
  "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
  "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
  "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York",
  "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
  "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
  "West Virginia", "Wisconsin", "Wyoming"
];
