
export const REVIEW_SEARCH_CONFIG = {
  INITIAL_LIMIT: 500,
  FINAL_RESULTS_LIMIT: 100,
  MIN_WORD_LENGTH: 3,
  SIMILARITY_THRESHOLD: 0.7,
  CITY_SIMILARITY_THRESHOLD: 0.7,
  ZIP_PROXIMITY_RANGE: 50,
  ZIP_PROXIMITY_MILES: 25,
  CITY_PROXIMITY_MILES: 25,
  CITY_GEOCODING_ENABLED: true,
  MAX_GEOCODING_CALLS_PER_SEARCH: 5,
  MINIMUM_SCORE_MULTI_FIELD: 4.0, // Increased from 2.0 for stricter filtering
  MINIMUM_MATCHES_MULTI_FIELD: 2,
  SCORES: {
    EXACT_ZIP_MATCH: 10,
    PREFIX_ZIP_MATCH: 5,
    SIMILARITY_MULTIPLIER: 3,
    WORD_MATCH: 1,
    PHONE_MATCH: 2.5,
    ADDRESS_SIMILARITY_MULTIPLIER: 2,
    CITY_SIMILARITY_MULTIPLIER: 1.5,
    CITY_PROXIMITY_MULTIPLIER: 2.5,
    ADDRESS_WORD_MATCH: 0.5,
    PROXIMITY_BASE: 2
  }
};
