// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcukyvewprttufbufybi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdWt5dmV3cHJ0dHVmYnVmeWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzY3NTEsImV4cCI6MjA2MjIxMjc1MX0.-Iq_Y-Ha4N9f6aKehaWPyJTV1CQUzjEA9OEgAZgcU1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);