require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'AparajitaCapacitorBiometricAuth', :path => '../../node_modules/@aparajita/capacitor-biometric-auth'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'mywelp' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  # Fix warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build
  # This suppresses the warning by marking the phase to not use dependency analysis
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |build_phase|
      if build_phase.respond_to?(:name) && build_phase.name == '[CP] Embed Pods Frameworks'
        build_phase.always_out_of_date = true
      end
    end
  end

  # Fix warning: WKProcessPool deprecation in Capacitor/Cordova
  # WKProcessPool is deprecated in iOS 15.0 but still works (multiple instances just have no effect)
  # This suppresses the deprecation warning for WKProcessPool in Capacitor dependencies
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Suppress WKProcessPool deprecation warnings
      config.build_settings['WARNING_CFLAGS'] ||= ['$(inherited)']
      config.build_settings['WARNING_CFLAGS'] << '-Wno-deprecated-declarations'
    end
  end

  # Fix warning: Search path for MetalToolchain not found
  # This cleans up invalid search paths that may have been cached by Xcode
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |config_name, config_file|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(config_name)
      if File.exist?(xcconfig_path)
        xcconfig = File.read(xcconfig_path)
        # Remove any MetalToolchain or DVTDownloads paths
        xcconfig_cleaned = xcconfig.gsub(/[^\s]*DVTDownloads[^\s]*/, '')
        xcconfig_cleaned = xcconfig_cleaned.gsub(/[^\s]*MetalToolchain[^\s]*/, '')
        File.write(xcconfig_path, xcconfig_cleaned)
      end
    end
  end
end
